version: "3.8"

services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
    environment:
      - MONGO_CONN_STR=mongodb://mongodb:27017/todos

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
      
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3500/api/tasks
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend

volumes:
  mongo-data: